Navigo:
  method:
    - GET
    - POST
    - PATCH
  path: /navigo
  controller: NavigoController
  middlewares:
    # - auth

NavigoByNumber:
  method:
    - GET
    - PATCH
  path: /navigo/:navigoNumber
  controller: NavigoController
  middlewares:
    # - auth

NavigoValidity:
  method:
    - POST
  path: /navigo/validity/:navigoNumber
  controller: NavigoController
  middlewares:
    # - auth

NavigoRenew:
  method:
    - POST
  path: /navigo/:navigoNumber/renew
  controller: NavigoController
  middlewares:
